# Generated by Django 5.1.5 on 2025-01-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('load', models.FloatField()),
                ('ap', models.IntegerField()),
                ('bullet_defence', models.IntegerField()),
                ('en_defence', models.IntegerField()),
                ('explosion_defence', models.IntegerField()),
                ('arm_load_capacity', models.FloatField()),
                ('price', models.FloatField()),
                ('manufacture', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('load', models.FloatField(default=0.0)),
                ('price', models.FloatField()),
                ('manufacture', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('load', models.FloatField()),
                ('ap', models.IntegerField()),
                ('bullet_defence', models.IntegerField()),
                ('en_defence', models.IntegerField()),
                ('explosion_defence', models.IntegerField()),
                ('stability', models.IntegerField()),
                ('output_correction', models.FloatField()),
                ('price', models.FloatField()),
                ('manufacture', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('load', models.FloatField(default=0.0)),
                ('price', models.FloatField()),
                ('manufacture', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('supply', models.FloatField()),
                ('price', models.FloatField()),
                ('manufacture', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('load', models.FloatField()),
                ('ap', models.IntegerField()),
                ('bullet_defence', models.IntegerField()),
                ('en_defence', models.IntegerField()),
                ('explosion_defence', models.IntegerField()),
                ('stability', models.IntegerField()),
                ('recovery_performance', models.IntegerField()),
                ('price', models.FloatField()),
                ('manufacture', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Legs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('load', models.FloatField(default=0.0)),
                ('ap', models.IntegerField()),
                ('bullet_defence', models.IntegerField()),
                ('en_defence', models.IntegerField()),
                ('explosion_defence', models.IntegerField()),
                ('stability', models.IntegerField()),
                ('leg_load_capacity', models.FloatField()),
                ('price', models.FloatField()),
                ('manufacture', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('load', models.FloatField(default=0.0)),
                ('is_left_arm', models.BooleanField()),
                ('is_right_arm', models.BooleanField()),
                ('is_left_shoulder', models.BooleanField()),
                ('is_right_shoulder', models.BooleanField()),
                ('price', models.FloatField()),
                ('manufacture', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
